### ISSUE TITLE
Local environment not building

### ISSUE THREAD

**Issue by rcuny** [Adyax/docman#1]
Hey,

I've been seeing your presentation at DrupalCon and wanted to give DocMan a try. I've ran into an issue which I managed to fix by changing 1 line in your code, but want to report it as it could be a bug. Let me be clear from the beginning: I'm not at all a Ruby developer, I'm a Drupal guy, I've just tried a quick edit but do not pretend to even have written that correctly :).

My test scenario is as follow:
- I've building a project with docroot + commons + sites + 2 projects, as per your template
- everything works fine and the files are correctly retrieved untill the last point, where the script enters into the "Docman::Application - Docman::Deployers::CommonDeployer" section.
- at that point, I get the following error:

```
E, [2014-12-02T10:16:56.127981 #10933] ERROR -- : Docman::Application - Operation failed: undefined method `has_key?' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/docman-0.0.42/lib/docman/deployers/deployer.rb:99:in `files_deployed?': undefined method `has_key?' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/docman-0.0.42/lib/docman/deployers/deployer.rb:95:in `deploy'
```

Looking at your code, it seems it's linked to this line in docman/deployers/deployer.rb

``` ruby
        return true unless self['environment'].has_key? 'target_checker'
```

altering to that solved the issue for me:

``` ruby
        return true unless self['environment'] && (self['environment'].has_key? 'target_checker')
```

nb: defining a local environment in config.yaml didn't help.

Have I missed something, or can you reproduce the error?
I can send you the full execution trace if needed.

Anyway, once this small change done, the local env is built, I'm gonna try now with deploying to stage. Thanks and congrats again for this tool, it's a great project!

Cheers,
Renaud

**Comment by aleksey-tk** [comment]
Hey rcuny, thanks for your feedback, we are looking into this!

**Comment by aroq** [comment]
Hello Renaud,

Your fix applied, indeed it fixed the issue that was possible with certain configurations.
Thanks!

**Comment by rcuny** [comment]
Hi Aroq,
Great, glad it helped :).
Cheers,
Renaud
